### ISSUE TITLE
BUG?

### ISSUE THREAD

**Issue by imRhoAias** [rhwong/unidbg-fetch-qsign-onekey#39]
at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign(QQSecuritySign.kt:56)
        at com.tencent.mobileqq.sign.QQSecuritySign.getSign$default(QQSecuritySign.kt:51)
        at moe.fuqiuluo.api.QsignKt.requestSign(qsign.kt:92)
        at moe.fuqiuluo.api.QsignKt.access$requestSign(qsign.kt:1)
        at moe.fuqiuluo.api.QsignKt$sign$2.invokeSuspend(qsign.kt:45)
        at moe.fuqiuluo.api.QsignKt$sign$2.invoke(qsign.kt)
        at moe.fuqiuluo.api.QsignKt$sign$2.invoke(qsign.kt)
        at io.ktor.server.routing.Route$buildPipeline$1$1.invokeSuspend(Route.kt:116)
        at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
        at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
        at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
        at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
        at io.ktor.server.routing.Routing.executeResult(Routing.kt:190)
        at io.ktor.server.routing.Routing.interceptor(Routing.kt:64)
        at io.ktor.server.routing.Routing$Plugin$install$1.invokeSuspend(Routing.kt:140)
        at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
        at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invokeSuspend(BaseApplicationEngine.kt:124)
        at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
        at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.server.application.hooks.CallFailed$install$1$1.invokeSuspend(CommonHooks.kt:45)
        at io.ktor.server.application.hooks.CallFailed$install$1$1.invoke(CommonHooks.kt)
        at io.ktor.server.application.hooks.CallFailed$install$1$1.invoke(CommonHooks.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
        at io.ktor.server.application.hooks.CallFailed$install$1.invokeSuspend(CommonHooks.kt:44)
        at io.ktor.server.application.hooks.CallFailed$install$1.invoke(CommonHooks.kt)
        at io.ktor.server.application.hooks.CallFailed$install$1.invoke(CommonHooks.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invokeSuspend(DefaultEnginePipeline.kt:118)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
        at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:119)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
        at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)
        at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: unicorn.UnicornException: No memory available or memory not present (UC_ERR_NOMEM)
        at unicorn.Unicorn.mem_map(Native Method)
        at com.github.unidbg.arm.backend.UnicornBackend.mem_map(UnicornBackend.java:134)
        ... 432 more

10月 14, 2023 2:06:10 下午 com.github.unidbg.AbstractEmulator handleEmuException
警告: emulate RX@0x4016d504[libfekit.so]0x16d504 exception sp=unidbg@0xbfffcc70, msg=mem_map address=0x41400000, size=402653184, perms=0x3, offset=58ms
[FEKit_]info: qq_sign.h:156 [GetSign] cmd:wtlogin.login

**Comment by imRhoAias** [comment]
使用1.2.1版本的80协议似乎容易寄

**Comment by rhwong** [comment]
此问题在降级至qsign1.2.1(20230917)依旧可以复现，是qsign的问题
一般只出现在登录时。
可以尝试修改txlib/8.9.80中的config.json为以下内容
`... "share_token": true, "count": 10, ... `为`... "share_token": false, "count": 1, ... `

**Comment by rhwong** [comment]
请尝试降级为`1.1.9-fix2`分支
如果go-cqhttp出现：`获取T544 sign时出现错误: encoding/hex: invalid byte: U+002F '/' (data: /custom_energy?...`错误，请重启go-cqhttp
